pipeline:
    docker:
        image: plugins/docker
        dockerfile: Dockerfile
        repo: sirboops/caddy
        tags: [0.11.1, latest]
        experimental: true
        squash: true
        secrets: [ docker_username, docker_password ]
